<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FourDotnet.BoogaBooster.DigitalTwin.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FourDotnet.BoogaBooster.DigitalTwin.Abstractions\FourDotnet.BoogaBooster.DigitalTwin.Abstractions.csproj" />
    <ProjectReference Include="..\..\Shared\FourDotnet.BoogaBooster.Core\FourDotnet.BoogaBooster.Core.csproj" />
  </ItemGroup>

</Project>
