<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Dapr.AspNetCore" Version="1.18.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire\FourDotnet.BoogaBooster.Aspire.ServiceDefaults\FourDotnet.BoogaBooster.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Shared\FourDotnet.BoogaBooster.IntegrationMessages\FourDotnet.BoogaBooster.IntegrationMessages.csproj" />
    <ProjectReference Include="..\Queue\FourDotnet.BoogaBooster.Queue\FourDotnet.BoogaBooster.Queue.csproj" />
    <ProjectReference Include="..\Weather\FourDotnet.BoogaBooster.Weather\FourDotnet.BoogaBooster.Weather.csproj" />
    <ProjectReference Include="..\DigitalTwin\FourDotnet.BoogaBooster.DigitalTwin\FourDotnet.BoogaBooster.DigitalTwin.csproj" />
  </ItemGroup>

</Project>
